### ISSUE TITLE
Integration with projectile

### ISSUE THREAD

**Issue by FrauH0lle** [mclear-tools/tabspaces#60]
Hey there!

Thanks a lot for creating tabspaces. I wanted to ask if there is any interest from your side to support projectile?

Projectile is pretty big part of my personal Emacs config and I was looking into tabspaces source which changes would need to be made in order to use projectile instead of project.el.

For example, there could be a variable like

```elisp
(defcustom tabspaces-projectile-integration nil
  "Whether to use projectile instead of project.el.
This variable must be set before tabspaces is loaded."
  :type 'boolean
  :group 'tabspaces)
```

which then controls how projects are switched, etc.

If yes, I can prepare a PR as soon as I am done.

**Comment by mclearc** [comment]
Thanks for this. I'm a bit torn because I recognize that lots of folks use projectile. However this package was written to just have built-in Emacs packages in mind. It's also written to be as simple as possible. So I am not inclined to add any features where I'll have to keep track of other packages.
