### ISSUE TITLE
`tabspaces-open-or-create-project-and-workspace` always creates new workspace, switch buffer always includes the buffer opened from in new workspace

### ISSUE THREAD

**Issue by JordanAnthonyKing** [mclear-tools/tabspaces#63]
In emacs 31, following the install instructions I'm not having success with either of these features.  When calling `tabspaces-open-or-create-project-and-workspace`  always creates new workspace regardless if one exists for that project.  Switch buffer will always include the buffer opened from in new workspace, i.e. I'm in project A, A.cpp, if I try to open project B and file b.html A.cpp will be listed in the workspace buffers for project B, nothing from B will be listed in the project buffers for A.

![image](https://github.com/user-attachments/assets/ae9a2cf0-6f6b-402d-852d-e7f80346b15a)

**Comment by mclearc** [comment]
Hi @JordanAnthonyKing -- I don't have Emacs 31, and since it is a development branch I'm not going to be bug testing it for quite some time -- at least until Emacs 30 is out. Once I've seen what changes have been made in Emacs 30 and where tab support is going development-wise in Emacs 31, I might have a better sense of what I need to update. Of course if you get a clearer idea as to what the issue is, feel free to post it here.
